### ISSUE TITLE
Is it possible to add syntax highlighting to files that do not have bnf/ebnf extension?

### ISSUE THREAD

**Issue by GaurangTandon** [vallentin/vscode-bnf#1]
An example would be the [Python Grammar file](https://github.com/python/cpython/blob/master/Grammar/Grammar). How do I apply your syntax highlighting on this file? 

For example, executing the syntax highlight option via a command pallette option on a file?

**Comment by vallentin** [comment]
If you want to get BNF highlighting (any file), then in the bottom right of VSCode it would say "Plain Text" (or the name of the language). Click it and in the language selection just pick BNF.

However next time you close and open the file, then you have to select the language again.

If you want VSCode to permanently highlight files named "Grammar" as BNF. Then go into the VSCode settings and find "File Associations". Then click "Edit in settings.json" and add the following:

```json
"files.associations": {
    "Grammar": "bnf"
}
```
