### ISSUE TITLE
EBNF comment not highlighted in the definition line containing '='

### ISSUE THREAD

**Issue by mmoderau** [vallentin/vscode-bnf#3]
When using a comment in EBNF syntax in the line containing the equals sign, the comment is not highlighted as a comment:

```
here = does (* not work *);

but =
   here (* it works *);
```

**Comment by vallentin** [comment]
Fixed.

![fixed](https://user-images.githubusercontent.com/17464404/83646853-81499180-a5b4-11ea-95f2-0ab6d0a1f07e.png)

I'll push a release later, just in case you find more issues.
